### ISSUE TITLE
Core_kernel.std doesn't exist anymore?

### ISSUE THREAD

**Issue by McYoloSwagHam** [BinaryAnalysisPlatform/bap-tutorial#6]
https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Core_kernel/index.html

I'm new to OCaml, but according to other people I contacted while trying to compile this `Core_kernel.Std` has been deprecated/removed

**Comment by ivg** [comment]
Agreed. We need to update the tutorial. I will work on it the next week.
